version: "3"
#### Server
services:
  server:
    build: ./server
    expose:
      - 8000
    environment:
      API_HOST: "http://localhost:3000/"
      APP_SERVER_PORT: 8000
    ports:
      - 8000:8000
    volumes:
      - ./server/src:/srv/app/server/src
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
  
  client:
    build: ./client
    environment:
      - REACT_APP_PORT=3000
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/srv/app/fullstack-client/src
      - ./client/src:/srv/app/fullstack-client/build
    links:
      - server
    command: yarn start